services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_test_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -h localhost -d users_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: app_user
      RABBITMQ_DEFAULT_PASS: app_password
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend

  user_service:
    build:
      context: ./services/user_service
    container_name: user_service
    restart: unless-stopped
    env_file:
      - ./services/user_service/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - backend

  product_service:
    build:
      context: ./services/product_service
    container_name: product_service
    restart: unless-stopped
    env_file:
      - ./services/product_service/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8001"
    networks:
      - backend

  cart_service:
    build:
      context: ./services/cart_service
    container_name: cart_service
    restart: unless-stopped
    env_file:
      - ./services/cart_service/.env
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8002:8002"
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
